name: Repo sync

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    name: Repo sync
    runs-on: [self-hosted, main]
    permissions:
      contents: write
    steps:

      - name: Push to public-origin
        run: |
          git clone https://${{ secrets.PUBLIC_ORIGIN_GITHUB_TOKEN }}@github.com/bidmachine/BidMachine-Google-Mobile-Ads-iOS-Adapters-private.git
          cd BidMachine-Google-Mobile-Ads-iOS-Adapters-private
          git remote add public-origin https://${{ secrets.PUBLIC_ORIGIN_GITHUB_TOKEN }}@github.com/bidmachine/BidMachine-Google-Mobile-Ads-iOS-Adapters.git || true
          git fetch public-origin
          git checkout master
          git push -f public-origin master:master
          cd ..
          rm -rf BidMachine-Google-Mobile-Ads-iOS-Adapters-private
